### ISSUE TITLE
Help needed - transmitter info dissapeared

### ISSUE THREAD

**Issue by zygmund2000** [NoobishSVK/fm-dx-webserver#38]
I don't know why but transmitter info from database suddenly dissapeared from my server, I tried to clean everything and setup from scratch and still  empty :(
Console log doesn't show any errors or warnings and other functions works correctly.
Have someone some idea how to trace this issue?

**Comment by kkonradpl** [comment]
There is an ongoing diversification of the data sources at maps.fmdx.pl. The Polish (POL) database now comes from RadioPolska instead of FMLIST.
I'm waiting for a dedicated API endpoint to include the inactive stations and RDS PS which is required for station identification in FM-DX Webserver. It should be fixed soon.

**Comment by NoobishSVK** [comment]
Try to restart your webserver and check if there's any change.

**Comment by zygmund2000** [comment]
Yes by this time it always shows info.
BTW @kkonradpl can I copy that database to my own server?

**Comment by NoobishSVK** [comment]
It's always possible to contact Konrad outside of this topic. You can also find him on our Discord server. Since the issue has been solved, I am locking this topic. Thank you for the report!
